# Generated by Django 5.0.6 on 2024-05-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersession_image_usersession_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='algorithm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='parameters',
            field=models.JSONField(),
        ),
    ]
