# Generated by Django 5.0.6 on 2024-05-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersession_crop_coords_usersession_filter_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='crop_coords',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='resize_dims',
        ),
        migrations.AddField(
            model_name='usersession',
            name='modifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='original_image',
            field=models.ImageField(upload_to='user_sessions/original_images/'),
        ),
    ]
