# Generated by Django 5.0.6 on 2024-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usersession_crop_coords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='modifications',
        ),
        migrations.AddField(
            model_name='usersession',
            name='crop_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='filter_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='resize_dims',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='original_image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='user_sessions/original_images/'),
        ),
    ]
