# Generated by Django 5.0.6 on 2024-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_usersession_modifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='silhouette_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
